name: command_center
description: "Command center of my bots"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.2.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.5
  get_it: ^7.6.4
  get_storage: ^2.0.3
  logger: ^1.1.0
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.6
  menu_bar: ^0.5.3
  cloud_firestore: ^4.17.0
  firebase_core: ^2.30.0
  equatable: ^2.0.5
  audioplayers: ^6.0.0
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/

