// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6T74Ngp3mO757489N_RndcZ2B3sAj1Jo',
    appId: '1:559411928066:web:171f565796ee2d7a751b1b',
    messagingSenderId: '559411928066',
    projectId: 'onemanco-b4de4',
    authDomain: 'onemanco-b4de4.firebaseapp.com',
    storageBucket: 'onemanco-b4de4.appspot.com',
    measurementId: 'G-6F0SD5S8XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6Tj3PTHn4ljoJO3zrn0xUHWZPsqkspw',
    appId: '1:559411928066:android:09abb8478ada37e0751b1b',
    messagingSenderId: '559411928066',
    projectId: 'onemanco-b4de4',
    storageBucket: 'onemanco-b4de4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzcwzGLfsk1Rb_UBtSSX6nYYb_hKHf4o',
    appId: '1:559411928066:ios:f43f09006facf062751b1b',
    messagingSenderId: '559411928066',
    projectId: 'onemanco-b4de4',
    storageBucket: 'onemanco-b4de4.appspot.com',
    iosBundleId: 'com.example.commandCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzcwzGLfsk1Rb_UBtSSX6nYYb_hKHf4o',
    appId: '1:559411928066:ios:f43f09006facf062751b1b',
    messagingSenderId: '559411928066',
    projectId: 'onemanco-b4de4',
    storageBucket: 'onemanco-b4de4.appspot.com',
    iosBundleId: 'com.example.commandCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6T74Ngp3mO757489N_RndcZ2B3sAj1Jo',
    appId: '1:559411928066:web:9c7bb3b8fecfe8aa751b1b',
    messagingSenderId: '559411928066',
    projectId: 'onemanco-b4de4',
    authDomain: 'onemanco-b4de4.firebaseapp.com',
    storageBucket: 'onemanco-b4de4.appspot.com',
    measurementId: 'G-SYCWSFNWNK',
  );
}
